name: Check Build

on: 
  workflow_dispatch:
  push:
    branches: [ dev ]
    paths-ignore: 
      - '**.md'
  pull_request:
    branches: [ dev ]
    paths-ignore: 
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs: 
  build:
   runs-on: ubuntu-latest
   strategy:
      matrix:
        os: [win-x64]
        configuration: [Release]
   steps:
    - uses: actions/checkout@v4
         
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
        
    - name: Build
      run: dotnet build --configuration ${{ matrix.configuration }}
      working-directory: src
    
    - name: Publish ${{ matrix.os }} ${{ matrix.configuration }} SWAPS
      working-directory: src/SWAPS
      run: |
        dotnet publish -c ${{ matrix.configuration }} \
        -r ${{ matrix.os }} \
        --self-contained \
        -p:PublishSingleFile=true \
        -p:DebugType=None \
        -p:IncludeNativeLibrariesForSelfExtract=true \
        -p:PublishTrimmed=true \
        -p:TrimMode=partial \
        -p:JsonSerializerIsReflectionEnabledByDefault=true

    - name: Publish ${{ matrix.os }} ${{ matrix.configuration }} SWAPS.Admin
      working-directory: src/SWAPS.Admin
      run: |
        dotnet publish -c ${{ matrix.configuration }} \
        -r ${{ matrix.os }} \
        --self-contained \
        -p:PublishSingleFile=true \
        -p:DebugType=None \
        -p:IncludeNativeLibrariesForSelfExtract=true \
        -p:PublishTrimmed=true \
        -p:TrimMode=partial \
        -p:JsonSerializerIsReflectionEnabledByDefault=true

    - name: Combine artifacts
      run: |
        mkdir buildtmp
        cp -a src/SWAPS/bin/${{ matrix.configuration }}/net8.0/${{ matrix.os }}/publish/. buildtmp/
        cp -a src/SWAPS.Admin/bin/${{ matrix.configuration }}/net8.0-windows/${{ matrix.os }}/publish/. buildtmp/
        cd buildtmp
        ls -lha
        zip -r all.zip .

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: all-${{ matrix.os }}
        path: |
          buildtmp/all.zip
        if-no-files-found: error
