name: Check Build

on: 
  workflow_dispatch:
  push:
    branches: [ develop ]
    paths-ignore: 
      - '**.md'
  pull_request:
    branches: [ develop ]
    paths-ignore: 
      - '**.md'

jobs: 
  build:
   runs-on: windows-latest
   strategy:
      matrix:
        os: [win-x64]
        configuration: [Release]
   steps:
    - uses: actions/checkout@v2.3.4
         
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    
    # Fixes https://github.com/actions/setup-dotnet/issues/155
    - run: dotnet nuget list source
        
    - name: Build
      run: dotnet build --configuration ${{ matrix.configuration }}
      working-directory: src
    
    - name: Publish ${{ matrix.os }} ${{ matrix.configuration }} SWAPS
      working-directory: src/SWAPS
      run: dotnet publish -c ${{ matrix.configuration }} -r ${{ matrix.os }} -p:PublishSingleFile=true -p:DebugType=None -p:PublishTrimmed=true

    - name: Publish ${{ matrix.os }} ${{ matrix.configuration }} SWAPS.Admin
      working-directory: src/SWAPS.Admin
      run: dotnet publish -c ${{ matrix.configuration }} -r ${{ matrix.os }} -p:PublishSingleFile=true -p:DebugType=None -p:PublishTrimmed=true

    - name: Combine artifacts
      run: |
        mkdir buildtmp
        Copy-Item -Recurse -Path "src/SWAPS/bin/${{ matrix.configuration }}/netcoreapp3.1/${{ matrix.os }}/publish/*" -Destination "buildtmp/" 
        Copy-Item -Recurse -Path "src/SWAPS.Admin/bin/${{ matrix.configuration }}/netcoreapp3.1/${{ matrix.os }}/publish/*" -Destination "buildtmp/"
        cd buildtmp
        dir
        Compress-Archive -Path * -DestinationPath all.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: all-${{ matrix.os }}
        path: |
          buildtmp/all.zip
        if-no-files-found: error
