name: Master CI

on: 
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
       upload_url: ${{ steps.create_draft.outputs.upload_url }}
       version: ${{ steps.create_draft.outputs.tag_name }}

    steps:
      - name: Release - Create Draft for a Release
        id: create_draft
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_variants:
    name: Build
    # windows-latest is required; building with linux results in NETSDK1100 error
    runs-on: windows-latest
    needs: [create_release]
    strategy:
      matrix:
        os: [win-x64, win-x86]
        configuration: [Release]
        project: [SWAPS]
        
    steps:
      - uses: actions/checkout@v2
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1'
        
      - name: Publish ${{ matrix.os }} ${{ matrix.configuration }} - dotnet publish 
        working-directory: ${{ matrix.project }}
        run: dotnet publish -c ${{ matrix.configuration }} -r ${{ matrix.os }} -p:PublishSingleFile=true -p:AssemblyVersion=${{ needs.create_release.outputs.version }} 
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.project }}-${{ matrix.os }}
          path: ${{ matrix.project }}/bin/${{ matrix.configuration }}/netcoreapp3.1/${{ matrix.os }}/publish/${{ matrix.project }}.exe
      
      - name: Pack ${{ matrix.os }} - Zip
        run: Compress-Archive ${{ matrix.project }}.exe ${{ matrix.project }}.zip
        working-directory: ${{ matrix.project }}/bin/${{ matrix.configuration }}/netcoreapp3.1/${{ matrix.os }}/publish/
        
      - name: Release ${{ matrix.os }} - Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }} 
          asset_path: ./${{ matrix.project }}/bin/${{ matrix.configuration }}/netcoreapp3.1/${{ matrix.os }}/publish/${{ matrix.project }}.zip
          asset_name: ${{ matrix.project }}-${{ matrix.os }}.zip
          asset_content_type: application/zip
  
